docs
mlabs-haskell/godot-cardano pull request #62
Opened 2024-05-08 14:45 UTC by brainrake

see #37

- [x] `nix build .#docs` static site generator
- [x] add readme to docs site
- [x] auto-generated api docs
- [x] generate navigation index
- [x] fix up links in generated documentation
- [x] docs commands in devenv
- [x] publish gh-pages
- [x] work around godot and gdscript-docs-maker bugs
- [x] fix pdf download

Generating docs for `provider.gd` crashes so it is removed, pending a fix in godot engine.
https://github.com/godotengine/godot/issues/81598

2024-06-21 11:57 UTC, brainrake commented on docs/default.nix
> +        # https://github.com/godotengine/godot/issues/81598
:(

2024-06-23 21:56 UTC, rmgaray requested changes
I can't say I understand yet how all of this comes together, but I did find an issue while testing out the PR.

I've tried adding a description to a file as explained [here](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html#documenting-a-script)  but the generator fails to include the brief description and also duplicates the description itself.

This is what I added at the beginning of `single_address_wallet.gd`:

```
extends RefCounted
## A brief description of the class.
##
## A longer description of what the class does and how to initialize it.

class_name SingleAddressWallet
``` 

But the generator creates this:

![imagen](https://github.com/mlabs-haskell/godot-cardano/assets/29001707/3aa6d7cf-70df-4f65-8950-02b247996697)

I noticed this because we need to revise our docs to properly follow the GDScript doc comment system (all of our descriptions are broken I believe).

2024-06-24 13:44 UTC, brainrake commented
Strangely, the built-in documentation system in godot editor (press F1, type class name) shows the description correctly. So it's probably either a bug in godot language server related code or the reference export script.

2024-06-24 17:01 UTC, rmgaray approved these changes
I like how the docs look and I have nothing to add to the implementation (we will have to do with these workarounds until some of the issues are fixed upstream). Good work, @brainrake !

2024-06-24 17:05 UTC, merged